### ISSUE TITLE
User defaults/MDM based autosetup

### ISSUE THREAD

**Issue by ygini** [talkingmoose/Outlook-Exchange-Setup-5#14]
It could be really awesome to support a settings based automatic setup. 

The main idea would be to improve existing setup by supporting 3 sources of settings in the following order:
- a dedicated user defaults domain
- the Mail MDM Exchange auto setup info
- the current hard coded value

First found used one and never again since Exchange have everything needed to manage mailbox migration.

**Comment by talkingmoose** [comment]
You've intrigued me. But to my knowledge, I can't manage Outlook setup with plists since Outlook doesn't use plists to manage accounts.

Am I misunderstanding your intention?

**Comment by ygini** [comment]
I don't want to manage outlook setup by plist but your AppleScript settings. 

Everything you've at the beginning of the scpt file who need to be customized for the setup.

**Comment by talkingmoose** [comment]
I think I understand now. You'd prefer I move all the "properties" from the beginning of the AppleScript to their own plist file? And make that plist file manageable via MDM using payload variables?

I've been planning to separate the settings from the script but hadn't considered the MDM possibilities.

**Comment by ygini** [comment]
It's exactly that. 

I want to be able to package script update via autopkg and push it automatically with Munki. 

For that I need setup strings extracted from the script file. 

And to deploy setting for anything, what's best than UserDefaults? It allow us to push settings via everything (file drop, payload free package, MDM, chef, puppet, etc.).

**Comment by talkingmoose** [comment]
I really like the plist idea and placing it in a manageable location.

Give me a while to noodle on this. It shouldn't be difficult, but I want to do it right.

**Comment by talkingmoose** [comment]
Closing this issue with plans to separate account setup data from scripts in a future version. Account setup data will likely move to an MDM manageable plist (such as net.talkingmoose.OutlookExchangeSetup6.plist) with fallback to hard coded values as suggested.

**Comment by ygini** [comment]
Any news on this topic?
