### ISSUE TITLE
Syntax error when saving

### ISSUE THREAD

**Issue by aporzio1** [talkingmoose/Outlook-Exchange-Setup-5#15]
When I try to save "Outlook Exchange Setup 5.3.0.scpt" I get the error "Can’t set «class wkOf» to true. Access not allowed."
![screen shot 2016-04-20 at 3 47 50 pm](https://cloud.githubusercontent.com/assets/7033289/14688168/44e14d52-070f-11e6-870c-ffa923cc5dd8.png)

**Comment by talkingmoose** [comment]
Looks like most of the classes are displaying as AppleScript's class names and not the friendly display names.

To compile this script, you'll need to save it on a Mac with Outlook 2016 installed and launched at least one time.

**Comment by talkingmoose** [comment]
Closing this issue after no follow up for 10 days.

**Comment by cornoir** [comment]
I am having the same error message but for version 5.5.0.  I have tried compiling on a Mac with Outlook 2016 (v 15.37) opened at least once.
