### ISSUE TITLE
Sierra MacOS 10.12 incompatible Build

### ISSUE THREAD

**Issue by ghost** [talkingmoose/Outlook-Exchange-Setup-5#17]
I couldn't get this to build on 10.12. Says where is ROOT folder than fails saying make sure in same directory. Moved to a 10.11 Machine, no issues. Seems to install and work fine on 10.12 once built. Just FYI
<img width="532" alt="screen shot 2016-09-26 at 2 27 57 pm" src="https://cloud.githubusercontent.com/assets/11448001/18848764/76fba34c-83f5-11e6-98b6-d761f406462a.png">
<img width="562" alt="screen shot 2016-09-26 at 2 27 44 pm" src="https://cloud.githubusercontent.com/assets/11448001/18848767/789479ae-83f5-11e6-8014-c9f738b68009.png">

**Comment by talkingmoose** [comment]
Thanks, @engineertrey! I'll look into it.

**Comment by talkingmoose** [comment]
@engineertrey, can you verify the "Package for Deployment.app" is in the **Outlook-Exchange-Setup-5-master > Package** folder? I've just run it on my macOS 10.12 Sierra machine and it creates the package.

<img width="437" alt="createpackage" src="https://cloud.githubusercontent.com/assets/877471/18881213/1fdd24fe-84a0-11e6-812b-2ede832d6841.png">

I'll also look at adding some code that puts the name of the app in quotes and offers to let you choose the ROOT folder if it can't find it.

**Comment by ghost** [comment]
You know I am using Icloud Desktop, That is where I had it on my Desktop, because I just copied it over via airdrop to a 10.11 and no Icloud and it worked. I wonder if that was it. I will try from another location.

**Comment by sovereign01** [comment]
Can confirm - I saw the same behaviour trying to build this on a 10.12.3 machine, was fine when the same folder structure was moved to a 10.11.x machine.

**Comment by daphatty** [comment]
I'm willing to bet this is a Gatekeeper problem. After slamming my head into a brick wall on 10.12, I came across this issue and tried to build the package on 10.11. That's when I noticed that I had to change the Gatekeeper option on my 10.11 Mac to "Anywhere" in order to build the package. Apple removed the "Anywhere" radial option from Gatekeeper in 10.12.

**Comment by rugbycubsf** [comment]
Same issue on 10.12.4. I thought the Gatekeeper was a great thing to check on and followed this to allow "Anywhere" http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/ but no go. Now I have to hunt for a 10.11 machine!

**Comment by talkingmoose** [comment]
Determined this issue stems from changes in newer versions of Mac OS, but I haven't found a way to address this in the script itself. I've posted a workaround thanks to @daphatty and @maccy on the Slack MacAdmins team.

[https://github.com/talkingmoose/Outlook-Exchange-Setup-5/wiki/Package-for-deployment](https://github.com/talkingmoose/Outlook-Exchange-Setup-5/wiki/Package-for-deployment)
