### ISSUE TITLE
Can't Get Working - Outlook "Set Up Your Email" Prompt

### ISSUE THREAD

**Issue by apizz** [talkingmoose/Outlook-Exchange-Setup-5#19]
We deployed this tool last July when the script was at 5.4.0.  However, after rebuilding w/ a fresh download of the tool, reentering all info in the AppleScript, and building a new PKG, I can't seem to get this working.

I've tested this on a MacBook Air (Early 2015) running 10.12.5 w/ Microsoft Office 2016 15.35.  We're running onprem Exchange.  I've tested two different accounts and even reimaged a test machine, but got the same result.

I can confirm that on initial login the root /Library LaunchAgent gets triggered and creates the ~/Library/LaunchAgents/net.talkingmoose.OutlookExchangeSetup5.plist file.  

![screen shot 2017-06-27 at 4 22 12 pm](https://user-images.githubusercontent.com/11789931/27608845-f0bea97a-5b56-11e7-9002-93b0a0147ed2.png)

I can also confirm the "dummy" ~/Library/Group Containers/UBF8T346G9.Office/OutlookProfile.plist file is created.  

![screen shot 2017-06-27 at 4 23 02 pm](https://user-images.githubusercontent.com/11789931/27608853-f84be61c-5b56-11e7-8cf4-504734cb81f5.png)

However, when Outlook is launched, while I have a Config Profile suppress the usual Office welcome / what's new prompts, I now see a "Set Up Your Email" window produced by Outlook.

![screen shot 2017-06-27 at 4 23 34 pm](https://user-images.githubusercontent.com/11789931/27608861-fdebf044-5b56-11e7-9d70-5d3fa94bb659.png)

I'm wondering if this is getting in the way, as even when I close this window I never see a dialog box as we did previously prompting for username and password to finish setting up the Exchange account.

**Comment by talkingmoose** [comment]
@apizz This is a known issue with versions 15.34 (I believe) and 15.35. You're seeing a new feature of Outlook that interferes with the script. Microsoft should be addressing it with the 15.36 release a little later this month where you can suppress this dialog using a configuration profile.

One workaround is to deploy the script with 15.33, but then you'll be three versions behind and that will trigger a full re-install of the applications at next update. If you can wait until July's 15.36 production release, I would encourage that.

I'm not sure if the fix is in the latest Insider Fast build (15.37) yet, but keep an eye on the #microsoft-office channel in the MacAdmins Slack team as well as [Outlook for Mac Insights Blog](https://blogs.msdn.microsoft.com/outlookformac/). One or both of those places should have details as we get closer.

**Comment by apizz** [comment]
@talkingmoose that's what I was reading.  Oh, how impeccable the timing just as I really start testing our image! XD

I'll keep an eye on the Slack channel.  Thanks for making such a great tool!

**Comment by SIXfoot5ins** [comment]
@talkingmoose Thanks for the heads up, I'm experiencing @apizz issue too

Hoping Outlook 15.36.0 drops soon as this new Set Up Your Email is stopping our rollout of Office 2016

**Comment by SIXfoot5ins** [comment]
15.36.0 was released yesterday, the Outlook Exchange Setup AppleScript now works without the "Set Up Your Email" dialog box getting in the way when using the OverrideAccountConfigurationWindow key

**Comment by apizz** [comment]
Interesting.  I can confirm that with 15.36 the set up your email is suppressed, but I still am not getting a prompt for the user to enter their username / pass on first launch triggered by the Exchange setup script.

We bind to AD and use local Exchange.

I can confirm in the OutloookExchangeSetup log file that the script is running and goes through the initial "Setup properties" but for whatever reason it doesn't get past that.  This is where it would pull the user info from AD and then create the account.  I can confirm from a production machine which we had successfully used this with last year that our setup properties settings are the same.

Below are the preferences we're deploying via profile

![screen shot 2017-07-12 at 1 26 12 pm](https://user-images.githubusercontent.com/11789931/28131020-9b722990-6706-11e7-9c04-837663141f29.png)

I tested running the AppleScript manually got the following error:

`error "The variable emailAddress is not defined." number -2753 from "emailAddress"`  I can see the portion in the AppleScript that's supposed to parse out the email address from the dscl command, but it's the subsequent `if emailAddress is "" then` (something went wrong) statement that the error refers to.

Thoughts on our issue @talkingmoose ?

**Comment by apizz** [comment]
I think this ultimately had more to do with permissions on the files themselves.  Regardless, this is now resolved for me.

**Comment by magicMac1** [comment]
@apizz I'm getting the same error:

`error "The variable emailAddress is not defined." number -2753 from "emailAddress"`

What was your fix?

**Comment by apizz** [comment]
@rqomsiya It wasn't actually a "fix" per se.  I didn't have time to effectively troubleshoot so I went back to our previous year's deployment of the 5.4.0 version of the script and its respective agents.  I'm pretty sure it had to do with permissions on the files as part of my own custom packaging.

Can you run an `ls -l` to get the permission details on the the Talking Moose script, the /Library/LaunchAgent and the ~/Library/LaunchAgent?

**Comment by magicMac1** [comment]
@apizz Thanks for quick response.. here are the permissions:

`-rw-r--r--  1 root  wheel  1574 Jun 13 20:09 /Library/LaunchAgents/net.talkingmoose.OutlookExchangeSetupLaunchAgent.plist`

`-rw-r--r--  1 ryq  CGUSER\Domain Users  890 Oct  6 15:56 /Users/ryq/Library/LaunchAgents/net.talkingmoose.OutlookExchangeSetup5.plist
`

**Comment by magicMac1** [comment]
@apizz So i got it working with the older version of hte script 5.4.0... i just have one last issue.. when it launches, it defaults to the "Conversation History" folder. Is there anyway to make it default to the Inbox?

**Comment by DeadByDawn101** [comment]
@rqomsiya @apizz does anyone have a vanilla 5.4.0 script? I am getting the The variable emailAddress is not defined." number -2753 from "emailAddress" error and it is driving me nuts,I ould like to try testing with the older script if possible.

thanks!
