### ISSUE TITLE
Failure looking up "mail" attribute instead of "EMailAddress"

### ISSUE THREAD

**Issue by Jaharmi** [talkingmoose/Outlook-Exchange-Setup-5#20]
Switching to "mail" instead of "EMailAddress" in version 5.5 of the AppleScript results in a failure in an environment I deal with.

- there is no attribute that _begins with_ "mail"; "mail" only available with `dscl /Search` when prefixed with "dsAttrTypeNative:"
- "EMailAddress" continues to be available as before, when the v5.4.0 script worked
- with the new `dscl /Search`, two attributes (duplicates) are returned for a cached mobile account, whereas the DS node-specific lookup returned only the single result from that DS node

Perhaps this critical attribute could be made into a variable, or several variants of the attribute could be tested when determining a value.

**Comment by talkingmoose** [comment]
I'll update this in a short while, but here's the quick fix for this:

Find this line:

`if paragraph i of userInformation begins with "mail:" then`

and replace it with this:

`if paragraph i of userInformation begins with "dsAttrTypeNative:mail:" then`

**Comment by bgowan** [comment]
Thanks for the help!

**Comment by talkingmoose** [comment]
I've revved the script to v5.5.1 to include the bug fix for the emailAddress error. If folks are able to test, please let me know what you find. Thanks!

**Comment by talkingmoose** [comment]
No further reports of this issue. Closing.
