### ISSUE TITLE
Run at first Outlook launch, way to bypass that?

### ISSUE THREAD

**Issue by el2493** [talkingmoose/Outlook-Exchange-Setup-5#21]
Hi,

This looks great, and the documentation is very good!  I noticed that this will only work successfully if it is installed before Outlook has been run.  For imaging purposes this makes total sense, but for testing purposes it makes it tricky since if I do something wrong I think I have to re-image computer or at the minimum uninstall/reinstall Office before I can try again.  

Do you know if there is a way to either delete or modify something to make Outlook think that it is the first time it's running again, or is there a way to change what the .PLIST file is checking for to have it check for something else (for example, if there are any email accounts set up) rather than checking to see if Outlook has run before?  I tried looking at the PLIST but I'm not great at reading them so couldn't figure out what I might need to change.  I thought maybe I could make Outlook think it was the first time it's running by going to Microsoft Outlook.app/Contents/SharedSupport/Outlook Profile Manager.app and deleting the profile, but I'm not sure if that worked because it's still not automatically setting up the account (though that be because I didn't do something right with the setup process).

Thanks

**Comment by el2493** [comment]
Nevermind, I think I found the answer on https://github.com/talkingmoose/Outlook-Exchange-Setup-5/wiki/Logging

Will try deleting UBF8T346G9.Office and trying again.

**Comment by el2493** [comment]
Nevermind, tried deleting the folder as well as just the OutlookProfile.plist and I don't think it worked. Account still isn't automatically configuring, and in the .log it went from acknowledging the files existed and doing nothing to acknowledging that the files didn't exist and still doing nothing.

**Comment by talkingmoose** [comment]
The package for placing the scripts doesn't necessarily need to be installed before or after Outlook is installed. It _does_ need to be installed prior to the first launch of Outlook for the user.

In testing, I generally recommend removing the testing account's home folder on the computer before testing again. Removing the entire home folder is a guaranteed way to ensure you've removed all files for the script. Enable Fast User Switching or use a VM to reduce the time between testing attempts.

**Comment by talkingmoose** [comment]
No further comments on this issue. Closing.
