### ISSUE TITLE
Configuration profile is not installed by package

### ISSUE THREAD

**Issue by VitosX** [talkingmoose/Outlook-Exchange-Setup-5#23]
Configuration profile preventing first launch dialogs is not installed by package.
Line 27 of postinstall package script does not work for me in macOS 10.11, 10.12 and 10.13, because of _/usr/bin/cd_ command. The binary is actually there, but does not work as intended. Using simple _cd_ solves the problem.

I wonder what was the reason for using absolute path for such basic shell builtin...

**Comment by talkingmoose** [comment]
Using full paths to binaries such as cd is a security measure to verify the script is using the correct system binary and not using a binary potentially set by malware.

I suggest you run `which cd` to determine the path to the binary you're using. It should still be `/usr/bin/cd`. If not, you should investigate why you have a different cd binary.

I do see one thing I'd change in that postinstall script. The full path to the folder should be `/private/tmp/Outlook Exchange Setup 5`. Either path should work, but this one is more complete.

**Comment by VitosX** [comment]
I understand the reason for using full paths, but in this case running external `/usr/bin/cd` "binary"
 (it is a script actually) will not work, because it spawns a new shell and exits afterwards. I think there is hardly any security implication in case of builtin shell commands, and `cd` is one of them.

`which cd` shows _/usr/bin/cd_ as expected, but `type cd` correctly reports _cd is a shell builtin_. 
`/tmp` vs `/private/tmp` does not matter in this case.

I still can't understand how this postinstall script could work in any configuration.

**Comment by talkingmoose** [comment]
Yep, point taken. I'll get this changed.

**Comment by talkingmoose** [comment]
This issue is corrected in 5.5.2. The postinstall script for the package now uses 'cd /private/tmp...' instead of '/usr/bin/cd /tmp...'.

Thanks, @VitosX!
