### ISSUE TITLE
Script issues on first launch Outlook 16.9

### ISSUE THREAD

**Issue by ssmurphy** [talkingmoose/Outlook-Exchange-Setup-5#24]
Hello and first thanks for making and sharing these great tools for the Mac Admin community.

We are working on a rollout of Office 365/2016 and are having an issue with the account build script with the new version of outlook 16.9.

The version of Office needs to activate before outlook 2016 will let you build an account. On first launch Outlook will ask to be activated and this works but the script to build the users account will not kick in. If you quit Outlook and relaunch the script runs as expected and the account builds without issue.

below is the output from the log file showing the first and second launch. Is there anything we can do to fix this?

Thanks again for your time.

Steven Murphy 

1/31/18 13:13:53 PM	Folder "/Users/redacted/Library/Group Containers/UBF8T346G9.Office" does not exist.
1/31/18 13:13:53 PM	Create folder "/Users/redacted/Library/Group Containters/UBF8T346G9.Office": Successful.
1/31/18 13:13:53 PM	Create empty file "/Users/redacted/Library/Group Containers/UBF8T346G9.Office/OutlookProfile.plist": Successful.
1/31/18 13:13:54 PM	Create folder "/Users/redacted/Library/LaunchAgents": Successful.
1/31/18 13:13:54 PM	Create launch agent "/Users/redacted/Library/LaunchAgents/net.talkingmoose.OutlookExchangeSetup5.plist": Successful.
1/31/18 13:13:54 PM	Set launch agent permissions to 644 (-rw-r--r--): Successful.
1/31/18 13:13:54 PM	Load launch agent: Successful.
1/31/18 1:14:52 PM	Starting Exchange account setup...
1/31/18 1:14:52 PM	Script: Outlook Exchange Setup 5.5.1

1/31/18 1:14:52 PM	Setup properties...
1/31/18 1:14:52 PM	Use Kerberos: false
1/31/18 1:14:52 PM	Exchange Server:redacted
1/31/18 1:14:52 PM	Exchange Server Requires SSL: redacted
1/31/18 1:14:52 PM	Exchange Server Port: redacted
1/31/18 1:14:52 PM	Directory Server: redacted
1/31/18 1:14:52 PM	Directory Server Requires Authentication: redacted
1/31/18 1:14:52 PM	Directory Server Requires SSL: redacted
1/31/18 1:14:52 PM	Directory Server SSL Port: redacted
1/31/18 1:14:52 PM	Directory Server Maximum Results: redacted
1/31/18 1:14:52 PM	Directory Server Search Base: 
1/31/18 1:14:52 PM	Get User Information from Active Directory: redacted

1/31/18 1:14:52 PM	Verify Email Address: true
1/31/18 1:14:52 PM	Verify Server Address: false
1/31/18 1:14:52 PM	Display Domain Prefix: false
1/31/18 1:14:52 PM	Download Headers Only: false
1/31/18 1:14:52 PM	Hide On My Computer Folders: true
1/31/18 1:14:52 PM	Unified Inbox: false
1/31/18 1:14:52 PM	Disable Autodiscover: true
1/31/18 1:14:52 PM	Error Message text: Outlook's setup for your Exchange account failed. Please contact the Help Desk for assistance at redacted or redacted.

1/31/18 1:14:52 PM	User information...
1/31/18 1:14:52 PM	First Name: redacted
1/31/18 1:14:52 PM	Last Name: redacted
1/31/18 1:14:52 PM	Email Address:redacted
1/31/18 1:14:52 PM	Department: redacted
1/31/18 1:14:52 PM	Office: redacted
1/31/18 1:14:52 PM	Company: redacted
1/31/18 1:14:52 PM	Work Phone: redacted
1/31/18 1:14:52 PM	Mobile Phone: redacted
1/31/18 1:14:52 PM	FAX: 
1/31/18 1:14:52 PM	Title: redactedR
1/31/18 1:14:52 PM	Street: redacted
1/31/18 1:14:52 PM	City: redacted
1/31/18 1:14:52 PM	State: redacted
1/31/18 1:14:52 PM	Postal Code: redacted
1/31/18 1:14:52 PM	Country: 
1/31/18 1:14:52 PM	Web Page: 

1/31/18 1:17:12 PM	Starting Exchange account setup...
1/31/18 1:17:12 PM	Script: Outlook Exchange Setup 5.5.1

1/31/18 1:17:13 PM	Setup properties...
1/31/18 1:17:13 PM	Use Kerberos: false
1/31/18 1:17:13 PM	Exchange Server: https://redacted
1/31/18 1:17:13 PM	Exchange Server Requires SSL: redacted
1/31/18 1:17:13 PM	Exchange Server Port: redacted
1/31/18 1:17:13 PM	Directory Server: redacted
1/31/18 1:17:13 PM	Directory Server Requires Authentication: redacted
1/31/18 1:17:13 PM	Directory Server Requires SSL: redacted
1/31/18 1:17:13 PM	Directory Server SSL Port: redacted
1/31/18 1:17:13 PM	Directory Server Maximum Results: redacted
1/31/18 1:17:13 PM	Directory Server Search Base: 
1/31/18 1:17:13 PM	Get User Information from Active Directory: redacted

1/31/18 1:17:13 PM	Verify Email Address: true
1/31/18 1:17:13 PM	Verify Server Address: false
1/31/18 1:17:13 PM	Display Domain Prefix: false
1/31/18 1:17:13 PM	Download Headers Only: false
1/31/18 1:17:13 PM	Hide On My Computer Folders: true
1/31/18 1:17:14 PM	Unified Inbox: false
1/31/18 1:17:14 PM	Disable Autodiscover: true
1/31/18 1:17:14 PM	Error Message text: Outlook's setup for your Exchange account failed. Please contact the Help Desk for assistance at redacted or redacted.

1/31/18 1:17:14 PM	User information...
1/31/18 1:17:14 PM	First Name: redacted
1/31/18 1:17:14 PM	Last Name: redacted
1/31/18 1:17:14 PM	Email Address: redacted
1/31/18 1:17:14 PM	Department: redacted
1/31/18 1:17:14 PM	Office: redacted
1/31/18 1:17:14 PM	Company: redacted
1/31/18 1:17:14 PM	Work Phone: redacted
1/31/18 1:17:14 PM	Mobile Phone: redacted
1/31/18 1:17:14 PM	FAX: 
1/31/18 1:17:14 PM	Title: redacted
1/31/18 1:17:14 PM	Street: redacted
1/31/18 1:17:14 PM	City: redacted
1/31/18 1:17:14 PM	State: redacted
1/31/18 1:17:14 PM	Postal Code: redacted
1/31/18 1:17:14 PM	Country: 
1/31/18 1:17:14 PM	Web Page: 

1/31/18 1:17:15 PM	Set Group Similar Folders to false: Successful.
1/31/18 1:17:15 PM	Set Hide On My Computer Folders to true: Successful.
1/31/18 1:17:27 PM	User verified email address as redacted.
1/31/18 1:17:27 PM	Create Exchange account: Successful.
1/31/18 1:17:27 PM	Populate Me Contact information: Successful.
1/31/18 1:17:27 PM	Set Outlook as default mail, calendar and contacts application: Successful.
1/31/18 1:17:32 PM	Delete OutlookExchangeSetup5.plist file from user LaunchAgents folder: Successful.
1/31/18 14:26:39 PM	/Users/redacted/Library/Group Containers/UBF8T346G9.Office folder already exists. Doing nothing.
1/31/18 14:26:39 PM	/Users/redacted/Library/Group Containers/UBF8T346G9.Office/OutlookProfile.plist already exists. Doing nothing.
1/31/18 14:26:39 PM	/Users/redacted/Library/LaunchAgents already exists. Doing nothing.
1/31/18 14:26:39 PM	/Users/redacted/Library/LaunchAgents/net.talkingmoose.OutlookExchangeSetup5.plist does not exist. Doing nothing.

**Comment by talkingmoose** [comment]
Sorry for the late response. Please, test with v5.5.2 uploaded February 18. I've fixed a handful of issues, a couple of which may cause the issue. In particular, I've added a new key/value pair to the profile to suppress an account setup window, which is new in Microsoft Outlook 15.36. I've also fixed a shebang problem keeping the profile from installing.

For best test results, always test under a clean macOS user account where Outlook has never been launched.

**Comment by ssmurphy** [comment]
Thanks for getting back to me on this. The updated version seems to have fixed the issues with the script not launching until outlook had been quit and relaunched that we had been seeing.

We found that with the following keys in place in the configuration profile that the show new items would pop up at each launch.

	<key>OUIWhatsNewShownItemIds</key>
	<array>
		<integer>1</integer>
		<integer>2</integer>
	</array>

So we removed them.

**Comment by talkingmoose** [comment]
Glad to hear that, Steven!

And thanks for letting me know about the new keys. I'll review them.

--

William Smith
Saint Paul, MN
bill@talkingmoose.net
(612) 384-8572

On 2/22/18, 1:46 PM, "ssmurphy" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for getting back to me on this. The updated version seems to have fixed the issues with the script not launching until outlook had been quit and relaunched that we had been seeing.

We found that with the following keys in place in the configuration profile that the show new items would pop up at each launch.

<key>OUIWhatsNewShownItemIds</key>

<array>

  <integer>1</integer>

  <integer>2</integer>

</array>

So we removed them.
