### ISSUE TITLE
Folder Ownership & Rights

### ISSUE THREAD

**Issue by mischkailjine** [talkingmoose/Outlook-Exchange-Setup-5#4]
Hi,

can anyone provide me the correct ownership / file / folder rights for /L/LA and /L/TMI/Scripts/ eg all files & folders (root:wheel, 755 or 777 ?)

If I run the AppleScript manually, while Outlook started, I get an Error "Syntax Error Can't set «class GrpF» to unified inbox.Access not allowed"

Thanx

Mischka

**Comment by poundbangbash** [comment]
/Library/LaunchAgents should be 644 root:wheel
/Library/TMI/Scripts should be 755 root:wheel

Not sure what's going on with the AppleScript.  Does Outlook already have an account setup? What do you see in the Result/Messages/Events/Replies section when running it manually?  Anything more than what you already reported above?

**Comment by mischkailjine** [comment]
Thanx, I will check and let You know...

**Comment by talkingmoose** [comment]
After completing the documentation for the scripts and launch agent, my plan is to create a packager to collect items together in a .pkg installer. I'll be sure to have it adjust permissions accordingly.

Curious if you've had continued issues with the AppleScript itself.

**Comment by mischkailjine** [comment]
it runs with the supplied access rights, but I'm still getting the "Syntax Error Can't set «class GrpF» to unified inbox.Access not allowed" Error. Another thing is that it gets configured with kerberos although I've set it to "false". Any Idea about that ? I will try the updated version tomorrow... Thanx in advance

**Comment by mischkailjine** [comment]
everything is running fine now... Thanx for Your help
