### ISSUE TITLE
Manage working offline

### ISSUE THREAD

**Issue by talkingmoose** [talkingmoose/Outlook-Exchange-Setup-5#6]
Set Outlook to work offline until the script is complete. Set it to work online after the user has read the "Setup complete" message and clicked the OK button.

**Comment by poundbangbash** [comment]
Can this also be made an option when implemented?  In my testing I haven't noticed the need for this behavior.

**Comment by talkingmoose** [comment]
I could make it an option but it's really for the user experience with the script itself. I've found if Outlook is the first application launched then the user is barraged with three dialogs at once:
Microsoft AutoUpdate needs permission to run.
End of script "Your account is ready" message.
Password prompt for Exchange or Office 365 account
I can't control the first message and I'd prefer to leave the "Your account is ready" message because it could also alert the user to a setup problem.

I could make the "success" message an option to not display at all and only alert the user to an error. That would negate the need for working offline/online.

Thoughts?

On 10/27/15, 12:37 PM, "eholtam" notifications@github.com wrote:

Can this also be made an option when implemented? In my testing I haven't noticed the need for this behavior.

**Comment by poundbangbash** [comment]
In my opinion I'd say leave the system online so it can start pulling data as soon as it is ready.  I suppress the account ready message and as soon as I get thru the MS dialogs of registering the O365 account it happily stars the email authorization prompt and downloads email. 

I think the scenario that a message pops up only if there is an error is the route to go.  If the account setup is successful it'll be obvious by the MS authentication prompt. No need to compete with that.

**Comment by talkingmoose** [comment]
Removed "success" message at end of AppleScript. Considering this redundant since Outlook will prompt for password on success. This also eliminates the need to set Outlook to work offline.
